/*
 * Builds docs/shape-gallery.md — every registered shape, grouped, so the whole
 * set can be eyeballed in one pass. Automated tests prove a shape draws inside
 * its box and round-trips; only a human can see that it looks right.
 *
 * Written to disk by scripts/generate-shape-gallery.ts (`pnpm gallery`).
 */

import { ALL_SHAPES, SHAPE_GROUPS } from './registry';

/** Node ids must be alphanumeric, but shape names contain hyphens. */
function idFor(name: string): string {
  return `n_${name.replace(/-/g, '_')}`;
}

export function buildGallery(): string {
  const lines: string[] = [
    '# Shape gallery',
    '',
    `Generated by \`pnpm gallery\`. ${ALL_SHAPES.length} shapes.`,
    '',
    'Open this file in the VS Code Markdown preview to see every shape rendered by',
    "ceasg's own positioned renderer. Each node is labelled with its canonical",
    'Mermaid name.',
    '',
  ];
  for (const group of SHAPE_GROUPS) {
    lines.push(`## ${group.title}`, '', '```mermaid', 'flowchart LR');
    for (const def of group.shapes) {
      lines.push(`  ${idFor(def.name)}@{ shape: ${def.name}, label: "${def.name}" }`);
    }
    lines.push('```', '');
  }
  return lines.join('\n');
}
